repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: flake8
        language: system
    -   id: pretty-format-json
        args: --autofix
        language: system
    -   id: check-json
    -   id: mixed-line-ending
        args: --fix lf